### ISSUE TITLE
multi address deposit

### ISSUE THREAD

**Issue by pedram1995kzm** [NabiKAZ/Coinex-API-PHP#1]
I'm trying to generate deposit address for each account of my exchange website users by using COINEX API I've faced a real problem imagine there is 2 users in my website and USER1 wants to deposit BTC so when he clicks on generate deposit address code runs : PUT /balance/deposit/address/BTC and address displays to him. but he hasn't used this address yet suddenly USER2 wants to deposit BTC too and then code runs again: PUT /balance/deposit/address/BTC but it says { code: 318, data: { }, message: "Deposit address not used." } should USER2 wait untill USER1 completes his deposit?! it can't be like that.. any idea for solving this? how everyone make an exchange with coinex api, it doesn't make a trouble for them?

**Comment by NabiKAZ** [comment]
Hi pedram,

Unfortunately, I have not experienced this and I do not have an exact answer, but these come to my mind:

- You may be able to use an interval between deposit requests or queue your customers' requests.
- Another idea is that when your customer makes a deposit, do not do it in coinex right away and just deposit on your site. But always have a good amount of liquidity backed up in your coinex account. Then periodically transfer money received from customers to coinex under a single deposit manually or via an automated API.
- And finally, maybe coinex itself has a method for this that I am unaware of and you should see the documentation.
- If your problem is not solved, I suggest you share it with the official coinex team:
https://github.com/coinexcom/coinex_exchange_api/issues

have a nice time.
